[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"

[profile.default.fuzz]
runs = 1000
dictionary_weight = 40
include_storage = true

[profile.default.invariant]
runs = 256

[profile.ci.fuzz]
runs = 100000

[profile.ci.invariant]
runs = 1000
depth = 256

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
